### PR TITLE
Feature  wordscreen(UI)

### PR DESCRIPTION
**Pull request by RasmusJemth**

### CODE REVIEW

**Comment by alfredgunnar** [comment]
MERGE

**Comment by ericwenn** [comment]
MERGE ONNNNN ME! MERGE ON ME!

**Comment by dasovm** [comment]
MERGE EATER!!!

**Comment by alfredgunnar** [comment]
MERGE MERGE MERGE MERGE MERGE MERGE MEEEEEEEERGE

**Comment by ericwenn** [comment]
MERGE ON THE WATER

**Comment by dasovm** [comment]
ALL GOOD THINGS COME TO A MERGE

**Comment by ericwenn** [comment]
YOU MERGE MY TRALALALA

**Comment by alfredgunnar** [comment]
ITSY BITSY TEENIE WEENIE YELLOW POLKA DOT MERGE

**Pull request merged**
