### PR TITLE
Added level model and data handler

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ericwenn** [comment]
Who let the merge out?

**Comment by ghost** [comment]
First

**Comment by alfredgunnar** [comment]
Billie Merge

**Comment by alfredgunnar** [comment]
Highway to merge

**Comment by ericwenn** [comment]
Wondermerge

**Comment by ericwenn** [comment]
I will always merge you

**Comment by ericwenn** [comment]
Smells like merge spirit

**Comment by alfredgunnar** [comment]
Merging rhapsody

**Comment by alfredgunnar** [comment]
I was made for merging you

**Comment by ericwenn** [comment]
My merge will always go on

**Comment by alfredgunnar** [comment]
The winner merge it all

**Comment by alfredgunnar** [comment]
Merge me baby one more time

**Comment by ericwenn** [comment]
När vindarna mergar mitt namn

**Comment by alfredgunnar** [comment]
What is merge, baby don't merge me, no more

**Comment by alfredgunnar** [comment]
Fångad av en mergevind

**Comment by ericwenn** [comment]
Fångad av en mergeconflict

**Pull request merged**
