### PR TITLE
Missions implemented.

### PR DESCRIPTION
**Pull request by ericwenn**

### CODE REVIEW

**Comment by ericwenn** [comment]
Merge merge merge!

**Comment by alfredgunnar** [comment]
Sounds awesome

**Comment by ghost** [comment]
Mergemerege

**Comment by dasovm** [comment]
I'll let you merge my lollipop

**Comment by ericwenn** [comment]
Rasmus och Daniel säger i kör: Merge merge merge!

**Comment by alfredgunnar** [comment]
Gotta merge dat branch

**Pull request merged**
